#!/usr/bin/bash

setxkbmap -layout us
setxkbmap -option caps:swapescape
nitrogen --restore
#hsetroot -solid \#D3869B
xrdb ~/.Xresources
#$HOME/.scripts/natscroll
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbar &
picom --experimental-backends &
sxhkd &
xsettingsd -c ~/.config/xsettingsd/xsettingsd-dwm.conf &
xfce4-power-manager --daemon &
dunst &
xidlehook --not-when-fullscreen --not-when-audio --timer 600 'slock' '' &
emacs --daemon &
mpd &

# Start gnome-keyring for ssh keys
eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# Start dbus-session
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
        eval 'dbus-launch --sh-syntax --exit-with-session'
fi

while true; do
    dwm 2> ~/.dwm.log
done

